# Generated by Django 5.2.15 on 2026-06-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Всего записей')),
                ('anomaly_count', models.PositiveIntegerField(default=0, verbose_name='Аномалий')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сессия анализа',
                'verbose_name_plural': 'Сессии анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=45, verbose_name='IP источника')),
                ('dest_ip', models.CharField(max_length=45, verbose_name='IP назначения')),
                ('protocol', models.CharField(max_length=20, verbose_name='Протокол')),
                ('packet_count', models.PositiveIntegerField(verbose_name='Пакетов')),
                ('byte_volume', models.PositiveIntegerField(verbose_name='Байт')),
                ('reconstruction_error', models.FloatField(verbose_name='Ошибка реконструкции')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Аномалия')),
                ('risk_level', models.CharField(choices=[('норма', 'Норма'), ('низкий', 'Низкий'), ('средний', 'Средний'), ('высокий', 'Высокий')], max_length=20, verbose_name='Уровень риска')),
                ('deviations_json', models.JSONField(default=list, verbose_name='Отклонения признаков')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='detector.analysissession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Запись трафика',
                'verbose_name_plural': 'Записи трафика',
                'ordering': ['-reconstruction_error'],
            },
        ),
    ]
